# Generated by Django 5.0.2 on 2024-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('mail', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.IntegerField()),
                ('fecha', models.DateField()),
                ('idproducto', models.IntegerField()),
                ('detalle_producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField()),
                ('fecha', models.DateField()),
                ('idproducto', models.IntegerField()),
                ('detalle_producto', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('stock_critico', models.IntegerField()),
                ('cantdisponible', models.IntegerField()),
            ],
        ),
    ]
